---
test:
  name: simple
  description: This is an example benchmark for caliper, to test the backend DLT's
    performance with simple account opening & querying transactions
  workers:
    type: local
    number: 1
  rounds:
  - label: open
    description: Test description for the opening of an account through the deployed chaincode
    txNumber: 500
    rateControl:
      type: fixed-rate
      opts:
        tps: 500
    arguments:
      money: 10000
    callback: benchmarks/scenario/simple/open.js
  - label: query
    description: Test description for the query performance of the deployed chaincode
    txNumber: 100
    rateControl:
      type: fixed-rate
      opts:
        tps: 100
    callback: benchmarks/scenario/simple/query.js
  - label: transfer
    description: Test description for transfering money between accounts
    txNumber: 1000
    rateControl:
          type: fixed-rate
          opts:
              tps: 1000
    arguments:
        money: 10000
    callback: benchmarks/scenario/simple/transfer.js
monitor:
  type:
  - docker
  docker:
    name:
    - all
  interval: 1
