---
test:
  name: smallbank
  description: This is smallbank benchmark for caliper
  workers:
    type: local
    number: 2
  rounds:
  - label: smallOperations
    txNumber: 1000
    rateControl:
      type: fixed-rate
      opts:
        tps: 1000
    arguments:
      accounts: 400
      txnPerBatch: 1
    callback: benchmarks/scenario/smallbank/smallbankOperations.js
  - label: query
    txNumber: 500
    rateControl:
      type: fixed-rate
      opts:
        tps: 50
    callback: benchmarks/scenario/smallbank/query.js
monitor:
  type: docker
  docker:
    name:
    - all
  interval: 1
